---
- name: Copy config to home directory
  become: yes
  copy:
    src: /vagrant/admin.conf
    dest: /home/ubuntu/admin.conf
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Update Environment
  become: yes
  lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG=/home/ubuntu/admin.conf'
    state: present

- name: Join Kubernetes Cluster
  become: yes
  shell: $(cat /vagrant/joinCommand.txt)
  # shell: "$(cat /tmp/joinCommand.txt | jq '.stdout_lines[0]' | sed 's/"//g')"
